### ISSUE TITLE
UPDATING PUDDLETAG: I would help but should I use pyqt5 or qtpy?

### ISSUE THREAD

**Issue by chincheta0815** [puddletag/puddletag#313]
Hi there,

would puddletag be able to run with pyqt5?
Is that a lot of effort to change that?

qt4 is kind of outdated on some systems (macos) so, I'd like to help/do the transition if necessary, but I need some starting advice... Where should I start, in which file etc....

I would only change the pyqt stuff using python2...

May qtpy (https://github.com/spyder-ide/qtpy), a wrapper, that support either pyqt4 or pyqt5 would be an option...

What do you think.
Before I start I would appreciate some input from keithgg, because it's host baby.

**Comment by keithgg** [comment]
qtpy seems reasonable. I'd say, try and convert the codebase to qtpy. If PyQt5 works out of the box, then be happy. If it doesn't then going rewriting to PyQt5 is the way to go.

Doing that is gonna be a pretty massive task because of the tight integration between PyQt4 and the way the code works (in some places making use of Qt facilities, where it might make sense to use Python for instance). 

As a result going PyQt5 with it's massive changes, you'll end up with a build that'd probably be broken until you're like 70% done with the work.

My suggestion is start with the main file (source/puddletag) and work your way from there. Disable all dialogs and config loading etc. Just get the tags loading into the main table and then work your way from there, piece by piece.

**Comment by chincheta0815** [comment]
Okay. I started as you mentioned.
Only thing to clarify: Is it okay for you to use qty or ist native PyQt5 better.
What's your opinion, considering maintenance etc.? I do not have that much experience in those things.

**Comment by keithgg** [comment]
Use qtpy. It could prove useful.

**Comment by sandrotosi** [comment]
We recently released 2.0.1 which contains the ports to python3 and pyqt5
