### ISSUE TITLE
Puddletag forum - can't register

### ISSUE THREAD

**Issue by Beckfield** [puddletag/puddletag#446]
I registered with the Puddletag forum on Sourceforge, but it won't send the activation email. Sorry to post this here, but I could find no other way to alert you to the problem.

**Comment by sandrotosi** [comment]
@keithgg do you think we still have any use for the [sourceforge forum](http://puddletag.sourceforge.net/forum/) ? there are no new posts/replies since more than 2 years, and this report seems to suggests new users cant even register anymore, so maybe it's time to disable it (and remove it from the `Help` menu)?

probably the entirety of https://sourceforge.net/projects/puddletag/ should be disabled/deleted or made it redirect to this project? i'm afraid only you can perform those operations, since you're the owner of that SF project

**Comment by keithgg** [comment]
I disabled registration ages ago, because we moved over to Github. At the time there were still open threads to sort. 

@sandrotosi Definitely remove the forum link from the help menu.

I'll keep the forum alive and disable everything else.
