### ISSUE TITLE
Actions - Fuctions getting re-ordered

### ISSUE THREAD

**Issue by sandrotosi** [puddletag/puddletag#509]
<a href="https://github.com/Kurt-Git"><img src="https://avatars2.githubusercontent.com/u/66940025?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kurt-Git](https://github.com/Kurt-Git)**
_Mon Jun 15 07:45:37 2020_
_Originally opened as https://github.com/sandrotosi/puddletag/issues/30_

----

I have an Action that has, so far, got 12 functions. The last two functions, Func10 & Func11 appear 3rd and 4th in my Action list. As these format my filename and dirname and are dependent on the successful completion of the previous fucntions it means I don't get the correct results.

I had a look at my puddletag.conf file and it had a reference to a puddleactions order file. I had a look at the file and all the fucntions are in the order I would expect them to be.

However the functions 1-9 do not have a leading zero. If I add a leading zero to the Func id the functions appear in the correct order in puddletag.

But after running puddletag and the Action the leading zeros are removed and I am back to having the functions in the wrong order.

Distro: Arch
Puddletag Version: Installed from AUR: puddletag-qt5-git r942.3c5e2dc-1

**Comment by tonurics** [comment]
I can confirm this is an issue and zero padding the function index numbers fixes the problem.

A quick fix, to add zero padding, change this line:
https://github.com/puddletag/puddletag/blob/e0d35889d70507dfd0a8dc00cf7c8e5361deba0f/source/puddlestuff/findfunc.py#L672

From:
`set_value = lambda i, key, value: cparser.set('Func%d' % i, key, value)`
To:
`set_value = lambda i, key, value: cparser.set('Func%03d' % i, key, value)`

Which will add double zero padding (i.e. 001, 002, 003, ...).

**Comment by tonurics** [comment]
Another option is to, change this line:
https://github.com/puddletag/puddletag/blob/e0d35889d70507dfd0a8dc00cf7c8e5361deba0f/source/puddlestuff/findfunc.py#L177

To:
`return funcname[4:].strip().zfill(3)`
Which will also double zero pad. When the actions are read from the Action's file, instead of when the file is written.

The more correct solution would be to change this line:
https://github.com/puddletag/puddletag/blob/e0d35889d70507dfd0a8dc00cf7c8e5361deba0f/source/puddlestuff/findfunc.py#L181

To a sorting method that is aware of natural numeric sorting, which would remove the need to zero pad. See: https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/

**Comment by sandrotosi** [comment]
@tonurics even for this bug, would you like to submit a PR for addressing it? you did all the investigative work already :)

**Comment by tonurics** [comment]
Done. Added natural sorting logic, forgoing the zero padding.

**Comment by sandrotosi** [comment]
closed via #536
