### ISSUE TITLE
Core dump on scroll

### ISSUE THREAD

**Issue by xeruf** [puddletag/puddletag#662]
```sh
❯ puddletag .
puddletag Version: 2.0.1
Locale: en_IE
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/puddlestuff/tagmodel.py", line 2465, in wheelEvent
    h.setValue(h.value() - numsteps)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
[1]    25979 abort (core dumped)  puddletag .
```
happens immediately when I try to scroll down with the mouse while the window has no scroll bar (all songs fit on one screen)

**Comment by herman-brix** [comment]
I'm seeing the same error since upgrading Python to 3.10 (Puddletag crashes at the slightest scroll-down when the number of tracks loaded does not fill the window vertically).

Python version 3.10.2
Puddletag version 2.1.1

Ugly **temporary** fix adapted from similar issue: https://github.com/polychromatic/polychromatic/issues/361

```
#         h.setValue(h.value() - numsteps)
         h.setValue(int(h.value() - numsteps))

```
