### ISSUE TITLE
Can't change any shortcut key

### ISSUE THREAD

**Issue by amithiel** [puddletag/puddletag#712]
Version used: 2.1.1
OS: Arch

Steps to reproduce:
- settings/shortcuts , double click any cell to change shortcut. It crashes instantly

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/puddlestuff/shortcutsettings.py", line 112, in paintEvent
    painter.drawRect(left - size, size * 0.5, size, size)
TypeError: arguments did not match any overloaded call:
  drawRect(self, QRectF): argument 1 has unexpected type 'float'
  drawRect(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawRect(self, QRect): argument 1 has unexpected type 'float'
Aborted (core dumped)
```

**Comment by amithiel** [comment]
Nope, just tried the mster branch. still crashes

**Comment by corubba** [comment]
I can't reproduce the issue with `master`, what error do you get? It can't be exactly the same as in your original report, because [line 112 of `puddlestuff/shortcutsettings.py`](https://github.com/puddletag/puddletag/blob/master/puddlestuff/shortcutsettings.py#L112) looks different on `master` (Notice the `QRectF`).

**Comment by amithiel** [comment]
you are right. my mistake, sorry
