### ISSUE TITLE
Show Full Codec In Columns

### ISSUE THREAD

**Issue by VaxisXC** [puddletag/puddletag#717]
is there anyway to have the column show the full codec in the columns? I am trying to have my files show if they're "MPEG 1 Layer 3" or something like "Free Lossless Audio Codec(reference libFLAC 1.3.2 20170101".

Apologies if this option already exists, I'm rather new to both puddletag and github. appreciate the help!

**Comment by corubba** [comment]
There is `__filetype` which gives you the type of the file (e.g. `MP3`, `MP4` or `FLAC`), and `__tag` which is the tag type (e.g. `ID3v2.4` or `VorbisComment`). Both of them are automatically provided by puddletag. Then there are a whole bunch of `encod*` tags which usually get added by the encoder when creating the files, but they don't have to be present. What specific piece of codec information are you looking for?

In general puddletag doesn't really care about the codec, all we need is the file-/container-type because that dictates which tag type to use: If it's MP3, use ID3; if it is OGG, use Vorbis; and so on. And you have that corner case with containers like mp4 or mkv/mka where you can have multiple tracks with different codecs in one file.

**Comment by VaxisXC** [comment]
Ahh ok, sorry it took so long to reply. I clearly didn't dig deep enough in the documentation. Thanks so much for the clarification. I just switched from using MP3tag on windows and was wanting a similar program for my laptop. Thanks again! Cheers!
